In [1]:
import pandas as pd

# Read only the first 5 rows to peek at structure — fast, low memory
df_sample = pd.read_csv("../data/raw/02-14-2018.csv", nrows=5)
df_sample

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0,0,0,0,56320859.5,139.300036,56320958,56320761,Benign
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0,0,0,0,56320733.0,114.551299,56320814,56320652,Benign
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0,0,0,0,56319311.5,301.934596,56319525,56319098,Benign
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,32,0,0,0,0,0.0,0.000000,0,0,Benign
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,32,0,0,0,0,0.0,0.000000,0,0,Benign

In [2]:
print(df_sample.columns.tolist())
print(f"\nTotal columns: {len(df_sample.columns)}")

['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

Total columns: 80

In [3]:
df_sample.dtypes

Dst Port           int64
Protocol           int64
Timestamp         object
Flow Duration      int64
Tot Fwd Pkts       int64
                  ...
Idle Mean        float64
Idle Std         float64
Idle Max           int64
Idle Min           int64
Label             object
Length: 80, dtype: object

In [4]:
df_sample2 = pd.read_csv("../data/raw/02-14-2018.csv", nrows=100000)
df_sample2.shape

(100000, 80)

In [1]:
df_sample2['Label'].value_counts()

NameError: name 'df_sample2' is not defined

In [2]:
import pandas as pd

df_sample = pd.read_csv("../data/raw/02-14-2018.csv", nrows=5)

In [3]:
df_sample2 = pd.read_csv("../data/raw/02-14-2018.csv", nrows=100000)
df_sample2.shape

(100000, 80)

In [4]:
df_sample2['Label'].value_counts()

Label
FTP-BruteForce    99885
Benign              115
Name: count, dtype: int64

In [5]:
df_sample2.describe()

,Dst Port,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,100000.000000,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.00000,1.000000e+05,100000.0,1.000000e+05,1.000000e+05,1.000000e+05,100000.000000,1.000000e+05,1.000000e+05
mean,21.507360,5.996770,7.263903e+04,1.005180,1.002430,0.374710,0.387770,0.161160,0.015640,0.052117,...,0.002470,39.96872,2.548666e+02,0.0,2.548666e+02,2.548666e+02,3.627705e+04,0.068702,3.627709e+04,3.627700e+04
std,70.458697,0.169469,2.837447e+06,0.350021,0.315064,33.608789,22.089976,8.805704,2.130906,3.948421,...,0.325246,1.05284,6.081476e+04,0.0,6.081476e+04,6.081476e+04,1.424514e+06,4.133604,1.424515e+06,1.424512e+06
min,0.000000,0.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
25%,21.000000,6.000000,1.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,40.00000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
50%,21.000000,6.000000,2.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,40.00000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
75%,21.000000,6.000000,2.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,40.00000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00
max,9984.000000,17.000000,1.126422e+08,91.000000,83.000000,7680.000000,2302.000000,1168.000000,300.000000,697.600000,...,90.000000,40.00000,1.840791e+07,0.0,1.840791e+07,1.840791e+07,5.632109e+07,775.696139,5.632164e+07,5.632080e+07

In [6]:
# Find columns where every value is the same (no variation at all)
constant_cols = [col for col in df_sample2.columns if df_sample2[col].nunique() <= 1]
print(f"Constant columns found: {len(constant_cols)}")
print(constant_cols)

Constant columns found: 15
['Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'FIN Flag Cnt', 'RST Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Active Std']

In [7]:
import sys
sys.path.append('../src')
from clean_data import load_and_clean

test_df = load_and_clean("../data/raw/03-01-2018.csv")  # smallest file, ~107MB
test_df.head()

ImportError: cannot import name 'load_and_clean' from 'clean_data' (d:\sih26153-data-pipeline\notebooks\../src\clean_data.py)

In [8]:
with open("../src/clean_data.py") as f:
    print(f.read())

In [1]:
import sys
sys.path.append('../src')
from clean_data import load_and_clean

test_df = load_and_clean("../data/raw/03-01-2018.csv")  # smallest file, ~107MB
test_df.head()

Loading ../data/raw/03-01-2018.csv ...
  Dropped 1834 rows with missing/infinite values
  Dropped 97 duplicate rows
  Final shape: (329193, 80)

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,2018-03-01 08:17:11,115307855,5,0,0,0,0,0,...,0,1812348,0,1812348,1812348,56700000,6010057.622,61000000,52500000,Benign
1,0,0,2018-03-01 08:20:07,60997457,2,0,0,0,0,0,...,0,0,0,0,0,61000000,0,61000000,61000000,Benign
2,67,17,2018-03-01 08:17:18,61149019,5,0,1500,0,300,300,...,8,3530939,0,3530939,3530939,19200000,12500000,32600000,7999725,Benign
3,0,0,2018-03-01 08:22:09,60997555,2,0,0,0,0,0,...,0,0,0,0,0,61000000,0,61000000,61000000,Benign
4,0,0,2018-03-01 08:24:11,61997503,3,0,0,0,0,0,...,0,999909,0,999909,999909,61000000,0,61000000,61000000,Benign

In [2]:
import pandas as pd

# Just peek at the header + a couple rows, no cleaning
df_check = pd.read_csv("../data/raw/02-20-2018.csv", nrows=5)
print(df_check.shape)
print(df_check.columns.tolist())

(5, 84)
['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

In [3]:
import pandas as pd
import os

processed_dir = "../data/processed"
files = sorted([f for f in os.listdir(processed_dir) if f.startswith("cleaned_") and f.endswith(".csv")])

print(f"Found {len(files)} cleaned files:\n{files}\n")

all_labels = {}
all_shapes = {}
column_sets = []

for f in files:
    path = os.path.join(processed_dir, f)
    df = pd.read_csv(path, nrows=None)  # full file, since we need accurate label counts
    all_shapes[f] = df.shape
    column_sets.append(tuple(df.columns.tolist()))
    labels = df['Label'].value_counts().to_dict()
    all_labels[f] = labels

print("=== SHAPES ===")
for f, shape in all_shapes.items():
    print(f"{f}: {shape}")

print("\n=== ALL FILES HAVE IDENTICAL COLUMNS? ===")
print(len(set(column_sets)) == 1)

print("\n=== LABEL DISTRIBUTION PER FILE ===")
for f, labels in all_labels.items():
    print(f"\n{f}:")
    for label, count in labels.items():
        print(f"  {label}: {count}")

Found 10 cleaned files:
['cleaned_02-14-2018.csv', 'cleaned_02-15-2018.csv', 'cleaned_02-16-2018.csv', 'cleaned_02-20-2018.csv', 'cleaned_02-21-2018.csv', 'cleaned_02-22-2018.csv', 'cleaned_02-23-2018.csv', 'cleaned_02-28-2018.csv', 'cleaned_03-01-2018.csv', 'cleaned_03-02-2018.csv']

=== SHAPES ===
cleaned_02-14-2018.csv: (819126, 80)
cleaned_02-15-2018.csv: (1038132, 80)
cleaned_02-16-2018.csv: (900988, 80)
cleaned_02-20-2018.csv: (7866855, 80)
cleaned_02-21-2018.csv: (1031018, 80)
cleaned_02-22-2018.csv: (1039693, 80)
cleaned_02-23-2018.csv: (1040255, 80)
cleaned_02-28-2018.csv: (470455, 80)
cleaned_03-01-2018.csv: (329193, 80)
cleaned_03-02-2018.csv: (1039072, 80)

=== ALL FILES HAVE IDENTICAL COLUMNS? ===
True

=== LABEL DISTRIBUTION PER FILE ===

cleaned_02-14-2018.csv:
  Benign: 662458
  SSH-Bruteforce: 117322
  FTP-BruteForce: 39346

cleaned_02-15-2018.csv:
  Benign: 986392
  DoS attacks-GoldenEye: 41455
  DoS attacks-Slowloris: 10285

cleaned_02-16-2018.csv:
  Benign: 446653
  DoS attacks-Hulk: 434873
  DoS attacks-SlowHTTPTest: 19462

cleaned_02-20-2018.csv:
  Benign: 7290680
  DDoS attacks-LOIC-HTTP: 576175

cleaned_02-21-2018.csv:
  DDOS attack-HOIC: 668461
  Benign: 360827
  DDOS attack-LOIC-UDP: 1730

cleaned_02-22-2018.csv:
  Benign: 1039331
  Brute Force -Web: 249
  Brute Force -XSS: 79
  SQL Injection: 34

cleaned_02-23-2018.csv:
  Benign: 1039691
  Brute Force -Web: 360
  Brute Force -XSS: 151
  SQL Injection: 53

cleaned_02-28-2018.csv:
  Benign: 402007
  Infilteration: 68448

cleaned_03-01-2018.csv:
  Benign: 236582
  Infilteration: 92611

cleaned_03-02-2018.csv:
  Benign: 756762
  Bot: 282310

In [4]:
import pandas as pd

file = "../data/raw/02-20-2018.csv"

df = pd.read_csv(file, nrows=1000, low_memory=False)

print("SHAPE:", df.shape)
print("\nCOLUMNS:")
print(df.columns.tolist())

print("\nDATA TYPES:")
print(df.dtypes)

print("\nFIRST 5 ROWS:")
print(df.head())

SHAPE: (1000, 84)

COLUMNS:
['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

DATA TYPES:
Flow ID       object
Src IP        object
Src Port       int64
Dst IP        object
Dst Port       int64
              ...
Idle Mean    float64
Idle Std     float64
Idle Max     float64
Idle Min     float64
Label         object
Length: 84, dtype: object

FIRST 5 ROWS:
                                  Flow ID          Src IP  Src Port  \
0  172.31.69.25-94.231.103.172-22-45498-6  94.231.103.172     45498
1                   8.0.6.4-8.6.0.1-0-0-0         8.6.0.1         0
2                   8.0.6.4-8.6.0.1-0-0-0         8.6.0.1         0
3                   8.0.6.4-8.6.0.1-0-0-0         8.6.0.1         0
4                   8.0.6.4-8.6.0.1-0-0-0         8.6.0.1         0

         Dst IP  Dst Port  Protocol            Timestamp  Flow Duration  \
0  172.31.69.25        22         6  20/02/2018 08:34:07         888751
1       8.0.6.4         0         0  20/02/2018 08:33:22      112642816
2       8.0.6.4         0         0  20/02/2018 08:36:11      112642712
3       8.0.6.4         0         0  20/02/2018 08:39:00      112642648
4       8.0.6.4         0         0  20/02/2018 08:41:49      112642702

   Tot Fwd Pkts  Tot Bwd Pkts  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0            11            11  ...                32            0           0
1             3             0  ...                 0            0           0
2             3             0  ...                 0            0           0
3             3             0  ...                 0            0           0
4             3             0  ...                 0            0           0

   Active Max  Active Min   Idle Mean   Idle Std    Idle Max    Idle Min  \
0           0           0         0.0   0.000000         0.0         0.0
1           0           0  56300000.0   7.071068  56300000.0  56300000.0
2           0           0  56300000.0  18.384776  56300000.0  56300000.0
3           0           0  56300000.0   5.656854  56300000.0  56300000.0
4           0           0  56300000.0  65.053824  56300000.0  56300000.0

    Label
0  Benign
1  Benign
2  Benign
3  Benign
4  Benign

[5 rows x 84 columns]

In [5]:
import pandas as pd
import numpy as np

file = "../data/raw/02-20-2018.csv"

df = pd.read_csv(file, nrows=1000, low_memory=False)

# Same columns that the cleaner removes
id_cols = ['Flow ID', 'Src IP', 'Src Port', 'Dst IP']
df = df.drop(columns=[c for c in id_cols if c in df.columns])

non_numeric = ['Timestamp', 'Label']
numeric_cols = [c for c in df.columns if c not in non_numeric]

print("Columns being treated as numeric:", len(numeric_cols))
print()

for col in numeric_cols:
    converted = pd.to_numeric(df[col], errors='coerce')
    bad_count = converted.isna().sum()

    if bad_count > 0:
        print(f"{col}: {bad_count}/1000 become NaN")
        print("Sample problematic values:")
        print(df.loc[converted.isna(), col].head(10).tolist())
        print()

Columns being treated as numeric: 78

In [6]:
import pandas as pd
import numpy as np

file = "../data/raw/02-20-2018.csv"

bad_summary = {}

for i, chunk in enumerate(
    pd.read_csv(file, low_memory=False, chunksize=200000)
):
    # Remove identity columns exactly like the cleaner
    id_cols = ['Flow ID', 'Src IP', 'Src Port', 'Dst IP']
    chunk = chunk.drop(columns=[c for c in id_cols if c in chunk.columns])

    numeric_cols = [
        c for c in chunk.columns
        if c not in ['Timestamp', 'Label']
    ]

    for col in numeric_cols:
        converted = pd.to_numeric(chunk[col], errors='coerce')
        bad = converted.isna().sum()

        if bad > 0:
            bad_summary[col] = bad_summary.get(col, 0) + bad

    if (i + 1) % 5 == 0:
        print(f"Checked chunk {i + 1}")

print("\n=== BAD VALUES SUMMARY ===")

if bad_summary:
    for col, count in sorted(bad_summary.items(), key=lambda x: -x[1]):
        print(f"{col}: {count}")
else:
    print("No non-numeric values found.")

Checked chunk 5
Checked chunk 10
Checked chunk 15
Checked chunk 20
Checked chunk 25
Checked chunk 30
Checked chunk 35
Checked chunk 40

=== BAD VALUES SUMMARY ===
Flow Byts/s: 36767

In [7]:
import pandas as pd
import numpy as np

file = "../data/raw/02-20-2018.csv"

total_rows = 0
rows_with_nan = 0

for chunk in pd.read_csv(file, low_memory=False, chunksize=200000):
    total_rows += len(chunk)
    rows_with_nan += chunk.isna().any(axis=1).sum()

print("Total rows:", total_rows)
print("Rows already containing NaN:", rows_with_nan)

Total rows: 7948748
Rows already containing NaN: 36767

In [8]:
import pandas as pd

file = "../data/raw/02-20-2018.csv"

df = pd.read_csv(file, low_memory=False)

print("RAW:", df.shape)

cleaned, stats = clean_chunk(df)

print("\nCLEANED:", cleaned.shape)
print("\nSTATS:")
print(stats)

MemoryError: Unable to allocate 60.6 MiB for an array with shape (7948748,) and data type int64

In [9]:
import pandas as pd
import os

file = "../data/processed/cleaned_02-20-2018.csv"

print("File exists:", os.path.exists(file))

if os.path.exists(file):
    df = pd.read_csv(file, nrows=5, low_memory=False)
    print("Columns:", len(df.columns))
    print("Column names:")
    print(df.columns.tolist())
    print("\nFirst 5 rows:")
    print(df.head())

File exists: True
Columns: 80
Column names:
['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

First 5 rows:
   Dst Port  Protocol            Timestamp  Flow Duration  Tot Fwd Pkts  \
0        22         6  2018-02-20 08:34:07         888751            11
1         0         0  2018-02-20 08:33:22      112642816             3
2         0         0  2018-02-20 08:36:11      112642712             3
3         0         0  2018-02-20 08:39:00      112642648             3
4         0         0  2018-02-20 08:41:49      112642702             3

   Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  \
0            11           1249.0           1969.0            736.0
1             0              0.0              0.0              0.0
2             0              0.0              0.0              0.0
3             0              0.0              0.0              0.0
4             0              0.0              0.0              0.0

   Fwd Pkt Len Min  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0              0.0  ...                32          0.0         0.0
1              0.0  ...                 0          0.0         0.0
2              0.0  ...                 0          0.0         0.0
3              0.0  ...                 0          0.0         0.0
4              0.0  ...                 0          0.0         0.0

   Active Max  Active Min   Idle Mean   Idle Std    Idle Max    Idle Min  \
0         0.0         0.0         0.0   0.000000         0.0         0.0
1         0.0         0.0  56300000.0   7.071068  56300000.0  56300000.0
2         0.0         0.0  56300000.0  18.384777  56300000.0  56300000.0
3         0.0         0.0  56300000.0   5.656854  56300000.0  56300000.0
4         0.0         0.0  56300000.0  65.053825  56300000.0  56300000.0

    Label
0  Benign
1  Benign
2  Benign
3  Benign
4  Benign

[5 rows x 80 columns]

In [10]:
import pandas as pd

file = "../data/processed/cleaned_02-20-2018.csv"

df = pd.read_csv(
    file,
    usecols=["Timestamp", "Label"],
    low_memory=False
)

df["Timestamp"] = pd.to_datetime(df["Timestamp"])

print("Earliest timestamp:", df["Timestamp"].min())
print("Latest timestamp:", df["Timestamp"].max())

print("\nFirst 10 timestamps:")
print(df["Timestamp"].head(10).to_string(index=False))

print("\nLast 10 timestamps:")
print(df["Timestamp"].tail(10).to_string(index=False))

print("\nDuplicate timestamps:", df["Timestamp"].duplicated().sum())

Earliest timestamp: 2018-02-20 01:00:00
Latest timestamp: 2018-02-20 12:59:59

First 10 timestamps:
2018-02-20 08:34:07
2018-02-20 08:33:22
2018-02-20 08:36:11
2018-02-20 08:39:00
2018-02-20 08:41:49
2018-02-20 08:45:21
2018-02-20 08:45:41
2018-02-20 08:44:38
2018-02-20 08:47:27
2018-02-20 08:52:18

Last 10 timestamps:
2018-02-20 02:58:56
2018-02-20 09:53:38
2018-02-20 10:37:52
2018-02-20 11:22:09
2018-02-20 08:37:22
2018-02-20 01:41:45
2018-02-20 11:51:06
2018-02-20 08:49:20
2018-02-20 02:00:54
2018-02-20 04:07:01

Duplicate timestamps: 7828383

In [11]:
import pandas as pd

file = "../data/processed/cleaned_02-20-2018.csv"

df = pd.read_csv(
    file,
    usecols=["Timestamp"],
    low_memory=False
)

df["Timestamp"] = pd.to_datetime(df["Timestamp"])

is_sorted = df["Timestamp"].is_monotonic_increasing

print("Is chronologically sorted?", is_sorted)

print("\nRows:", len(df))

print("Time range:")
print(df["Timestamp"].min(), "→", df["Timestamp"].max())

Is chronologically sorted? False

Rows: 7866855
Time range:
2018-02-20 01:00:00 → 2018-02-20 12:59:59

In [1]:
import pandas as pd
import os

processed_dir = "../data/processed"
files = sorted([f for f in os.listdir(processed_dir) if f.startswith("cleaned_") and f.endswith(".csv")])

# CHECK 1: constant columns across all files
constant_per_file = {}
for f in files:
    df = pd.read_csv(os.path.join(processed_dir, f))
    constant_per_file[f] = set([col for col in df.columns if df[col].nunique() <= 1])
    del df

always_constant = set.intersection(*constant_per_file.values())
sometimes_constant = set.union(*constant_per_file.values()) - always_constant
print("CHECK 1 — Always constant (safe to drop):", always_constant)
print("CHECK 1 — Sometimes constant (keep):", sometimes_constant)

# CHECK 2: overall label counts combined across all files
label_totals = {}
for f in files:
    df = pd.read_csv(os.path.join(processed_dir, f))
    counts = df['Label'].value_counts().to_dict()
    for label, count in counts.items():
        label_totals[label] = label_totals.get(label, 0) + count
    del df

print("\nCHECK 2 — Combined label totals across all 10 files:")
for label, count in sorted(label_totals.items(), key=lambda x: -x[1]):
    print(f"  {label}: {count}")

# CHECK 3: timestamp range per file (confirms chronological order, needed for windowing)
print("\nCHECK 3 — Timestamp range per file:")
for f in files:
    df = pd.read_csv(os.path.join(processed_dir, f), usecols=['Timestamp'], parse_dates=['Timestamp'])
    print(f"  {f}: {df['Timestamp'].min()} to {df['Timestamp'].max()}")
    del df

CHECK 1 — Always constant (safe to drop): {'Bwd Blk Rate Avg', 'Fwd Pkts/b Avg', 'Bwd Byts/b Avg', 'Bwd URG Flags', 'Bwd PSH Flags', 'Fwd Byts/b Avg', 'Bwd Pkts/b Avg', 'Fwd Blk Rate Avg'}
CHECK 1 — Sometimes constant (keep): {'Fwd URG Flags', 'CWE Flag Count'}

CHECK 2 — Combined label totals across all 10 files:
  Benign: 13221383
  DDOS attack-HOIC: 668461
  DDoS attacks-LOIC-HTTP: 576175
  DoS attacks-Hulk: 434873
  Bot: 282310
  Infilteration: 161059
  SSH-Bruteforce: 117322
  DoS attacks-GoldenEye: 41455
  FTP-BruteForce: 39346
  DoS attacks-SlowHTTPTest: 19462
  DoS attacks-Slowloris: 10285
  DDOS attack-LOIC-UDP: 1730
  Brute Force -Web: 609
  Brute Force -XSS: 230
  SQL Injection: 87

CHECK 3 — Timestamp range per file:
  cleaned_02-14-2018.csv: 1970-01-05 03:01:17 to 2018-02-14 12:59:59
  cleaned_02-15-2018.csv: 2018-02-15 01:00:00 to 2018-02-15 12:59:59
  cleaned_02-16-2018.csv: 2018-02-16 01:00:32 to 2018-02-16 12:58:24
  cleaned_02-20-2018.csv: 2018-02-20 01:00:00 to 2018-02-20 12:59:59
  cleaned_02-21-2018.csv: 2018-02-21 01:55:46 to 2018-02-21 10:43:21
  cleaned_02-22-2018.csv: 1970-01-10 03:04:26 to 2018-02-22 12:59:59
  cleaned_02-23-2018.csv: 2018-02-23 01:00:00 to 2018-02-23 12:59:59
  cleaned_02-28-2018.csv: 2018-02-28 01:00:00 to 2018-02-28 12:59:59
  cleaned_03-01-2018.csv: 2018-03-01 01:00:00 to 2018-03-01 12:59:59
  cleaned_03-02-2018.csv: 2018-03-02 01:00:00 to 2018-03-02 12:59:59

In [2]:
import pandas as pd
import numpy as np
import os

# ============================================================
# CHANGE ONLY THIS PATH
# ============================================================
FILE = "../data/processed/your_final_vector_file.csv"

print("=" * 70)
print("FINAL DATA / VECTOR PIPELINE AUDIT")
print("=" * 70)

# ------------------------------------------------------------
# 1. FILE CHECK
# ------------------------------------------------------------
print("\n[1] FILE")
print("Exists:", os.path.exists(FILE))

if not os.path.exists(FILE):
    print("ERROR: File not found. Change FILE path and run again.")
else:

    # --------------------------------------------------------
    # 2. LOAD
    # --------------------------------------------------------
    print("\n[2] LOADING DATA...")
    df = pd.read_csv(FILE, low_memory=False)

    print("Shape:", df.shape)
    print("Rows:", len(df))
    print("Columns:", len(df.columns))

    # --------------------------------------------------------
    # 3. COLUMNS
    # --------------------------------------------------------
    print("\n[3] COLUMNS")
    print(df.columns.tolist())

    # --------------------------------------------------------
    # 4. DATA TYPES
    # --------------------------------------------------------
    print("\n[4] DATA TYPES")
    print(df.dtypes.value_counts())

    # --------------------------------------------------------
    # 5. TIMESTAMP CHECK
    # --------------------------------------------------------
    if "Timestamp" in df.columns:
        ts = pd.to_datetime(df["Timestamp"], errors="coerce")

        print("\n[5] TIMESTAMP")
        print("Invalid timestamps:", ts.isna().sum())
        print("Earliest:", ts.min())
        print("Latest:", ts.max())
        print("Chronologically sorted:",
              ts.is_monotonic_increasing)

    else:
        print("\n[5] TIMESTAMP")
        print("No Timestamp column found.")

    # --------------------------------------------------------
    # 6. MISSING / INFINITE VALUES
    # --------------------------------------------------------
    print("\n[6] DATA QUALITY")

    print("Total NaN values:", df.isna().sum().sum())

    numeric_df = df.select_dtypes(include=[np.number])

    print("Total infinite values:",
          np.isinf(numeric_df).sum().sum())

    # Show columns with NaN
    nan_cols = df.isna().sum()
    nan_cols = nan_cols[nan_cols > 0]

    if len(nan_cols) > 0:
        print("\nColumns containing NaN:")
        print(nan_cols.sort_values(ascending=False))
    else:
        print("No NaN values found.")

    # --------------------------------------------------------
    # 7. LABEL CHECK
    # --------------------------------------------------------
    if "Label" in df.columns:
        print("\n[7] LABEL DISTRIBUTION")
        print(df["Label"].value_counts(dropna=False))

        print("\nNumber of unique labels:",
              df["Label"].nunique())

    else:
        print("\n[7] LABEL")
        print("No Label column found.")

    # --------------------------------------------------------
    # 8. NUMERIC FEATURE SUMMARY
    # --------------------------------------------------------
    print("\n[8] NUMERIC FEATURES")

    numeric_cols = df.select_dtypes(include=[np.number]).columns

    print("Number of numeric columns:", len(numeric_cols))

    print("\nFirst numeric columns:")
    print(list(numeric_cols[:20]))

    # --------------------------------------------------------
    # 9. CHECK FOR CONSTANT FEATURES
    # --------------------------------------------------------
    if len(numeric_cols) > 0:
        unique_counts = df[numeric_cols].nunique()

        constant_cols = unique_counts[unique_counts <= 1]

        print("\n[9] CONSTANT FEATURES")
        print("Number of constant features:",
              len(constant_cols))

        if len(constant_cols) > 0:
            print(constant_cols)

    # --------------------------------------------------------
    # 10. VECTOR / STATE DETECTION
    # --------------------------------------------------------
    print("\n[10] VECTOR / STATE CHECK")

    possible_state_cols = [
        c for c in df.columns
        if "state" in c.lower()
        or "window" in c.lower()
        or "sequence" in c.lower()
        or "vector" in c.lower()
    ]

    if possible_state_cols:
        print("Possible state/window/sequence columns:")
        print(possible_state_cols)
    else:
        print("No obvious state/window/sequence column names found.")

    # --------------------------------------------------------
    # 11. FIRST 5 ROWS
    # --------------------------------------------------------
    print("\n[11] FIRST 5 ROWS")
    print(df.head().to_string())

    # --------------------------------------------------------
    # 12. LAST 5 ROWS
    # --------------------------------------------------------
    print("\n[12] LAST 5 ROWS")
    print(df.tail().to_string())

    # --------------------------------------------------------
    # 13. SUMMARY
    # --------------------------------------------------------
    print("\n" + "=" * 70)
    print("AUDIT COMPLETE")
    print("=" * 70)

======================================================================
FINAL DATA / VECTOR PIPELINE AUDIT
======================================================================

[1] FILE
Exists: False
ERROR: File not found. Change FILE path and run again.

In [3]:
import json
import numpy as np
import os

MODEL_DIR = "../data/processed/model_ready"

# -------------------------
# Metadata
# -------------------------
with open(os.path.join(MODEL_DIR, "metadata.json"), "r") as f:
    metadata = json.load(f)

print("=" * 60)
print("METADATA")
print("=" * 60)

print("Window size:", metadata["window_seconds"], "seconds")
print("Sequence length:", metadata["sequence_length"])
print("Number of features:", metadata["n_features"])
print("Files processed:", metadata["files_processed"])
print("Files failed:", metadata["files_failed"])

print("\nLabel classes:")
for i, label in enumerate(metadata["label_classes"]):
    print(i, "->", label)

print("\nSaved shapes:")
for name, shape in metadata["shapes"].items():
    print(name, ":", shape)

# -------------------------
# Dataset arrays
# -------------------------
data = np.load(os.path.join(MODEL_DIR, "dataset.npz"))

print("\n" + "=" * 60)
print("ACTUAL DATASET SHAPES")
print("=" * 60)

for key in data.files:
    print(key, ":", data[key].shape)

# -------------------------
# Check values
# -------------------------
print("\n" + "=" * 60)
print("DATA QUALITY")
print("=" * 60)

for key in ["X_train", "X_val", "X_test"]:
    arr = data[key]
    print(
        key,
        "| NaN:", np.isnan(arr).sum(),
        "| Inf:", np.isinf(arr).sum()
    )

# -------------------------
# Label distribution
# -------------------------
print("\n" + "=" * 60)
print("LABEL DISTRIBUTION")
print("=" * 60)

classes = metadata["label_classes"]

for key in ["y_train", "y_val", "y_test"]:
    y = data[key]

    print("\n", key)

    unique, counts = np.unique(y, return_counts=True)

    for label_id, count in zip(unique, counts):
        label_name = classes[int(label_id)]
        print(f"{label_id:2d} -> {label_name:30s} {count}")

============================================================
METADATA
============================================================
Window size: 30 seconds
Sequence length: 10
Number of features: 72
Files processed: 10
Files failed: []

Label classes:
0 -> Benign
1 -> Bot
2 -> DDOS attack-HOIC
3 -> DDOS attack-LOIC-UDP
4 -> DoS attacks-GoldenEye
5 -> DoS attacks-Hulk
6 -> DoS attacks-SlowHTTPTest
7 -> Infilteration
8 -> SSH-Bruteforce

Saved shapes:
X_train : [6766, 10, 72]
X_val : [1451, 10, 72]
X_test : [1457, 10, 72]

============================================================
ACTUAL DATASET SHAPES
============================================================
X_train : (6766, 10, 72)
y_train : (6766,)
X_val : (1451, 10, 72)
y_val : (1451,)
X_test : (1457, 10, 72)
y_test : (1457,)

============================================================
DATA QUALITY
============================================================
X_train | NaN: 0 | Inf: 0
X_val | NaN: 0 | Inf: 0
X_test | NaN: 0 | Inf: 0

============================================================
LABEL DISTRIBUTION
============================================================

 y_train
 0 -> Benign                         6229
 1 -> Bot                            52
 2 -> DDOS attack-HOIC               15
 4 -> DoS attacks-GoldenEye          24
 5 -> DoS attacks-Hulk               2
 6 -> DoS attacks-SlowHTTPTest       86
 7 -> Infilteration                  195
 8 -> SSH-Bruteforce                 163

 y_val
 0 -> Benign                         1289
 1 -> Bot                            60
 3 -> DDOS attack-LOIC-UDP           10
 6 -> DoS attacks-SlowHTTPTest       7
 7 -> Infilteration                  85

 y_test
 0 -> Benign                         1433
 3 -> DDOS attack-LOIC-UDP           24

In [1]:
import pandas as pd
import numpy as np

# 1. Load ONE raw CSV file (replace with your actual file path)
file_path = "path/to/your/cic_ids_2018_day_x.csv"
print(f"Loading data from {file_path}...")
df = pd.read_csv(file_path)

# Ensure Timestamp is a datetime object for windowing
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

# 2. Check raw flow-level class distribution
print("\n--- Raw Flow-Level Class Distribution ---")
print(df['Label'].value_counts())

# 3. Simulate 30-second windowing to test Fix 2
# Calculate the percentage of each label within every 30-second window
windowed = df.groupby(pd.Grouper(key='Timestamp', freq='30s'))['Label'].value_counts(normalize=True).unstack(fill_value=0)

# 4. Apply the Old Rule (Majority > 50%)
def get_majority_label(row):
    top_label = row.idxmax()
    return top_label if row[top_label] > 0.50 else 'Benign'

old_rule_labels = windowed.apply(get_majority_label, axis=1)

# 5. Apply the New Rule (Threshold > 5%)
def get_threshold_label(row):
    # Drop Benign to focus on attack thresholds
    attack_cols = [col for col in row.index if col != 'Benign']
    if not attack_cols:
        return 'Benign'
    
    # Find the attack with the highest percentage
    attacks = row[attack_cols]
    top_attack = attacks.idxmax()
    
    # If the top attack is > 5%, label it as that attack
    if attacks[top_attack] > 0.05:
        return top_attack
    return 'Benign'

new_rule_labels = windowed.apply(get_threshold_label, axis=1)

# 6. Compare the Results
print("\n--- Window Labels: OLD RULE (>50% Majority) ---")
print(old_rule_labels.value_counts())

print("\n--- Window Labels: NEW RULE (>5% Threshold) ---")
print(new_rule_labels.value_counts())

Loading data from path/to/your/cic_ids_2018_day_x.csv...

FileNotFoundError: [Errno 2] No such file or directory: 'path/to/your/cic_ids_2018_day_x.csv'

In [1]:
import numpy as np
import joblib

# 1. Load the generated dataset and the label encoder
data_path = "../data/processed/model_ready/dataset.npz"
encoder_path = "../data/processed/model_ready/label_encoder.joblib"

print("Loading dataset...")
data = np.load(data_path)
X_train, y_train = data['X_train'], data['y_train']

label_encoder = joblib.load(encoder_path)

# 2. Verify the shapes (Checking Fix 1: 71 features instead of 72)
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}\n")

# 3. Decode the labels and check the distribution (Checking Fix 2: Rescued classes)
y_train_decoded = label_encoder.inverse_transform(y_train)
unique_classes, counts = np.unique(y_train_decoded, return_counts=True)

print("--- Final Training Set Class Distribution ---")
for cls, count in zip(unique_classes, counts):
    print(f"{cls}: {count}")

Loading dataset...
X_train shape: (6766, 10, 71)
y_train shape: (6766,)

--- Final Training Set Class Distribution ---
Benign: 5521
Bot: 362
Brute Force -Web: 25
Brute Force -XSS: 111
DDOS attack-HOIC: 46
DDoS attacks-LOIC-HTTP: 24
DoS attacks-GoldenEye: 33
DoS attacks-Hulk: 8
DoS attacks-SlowHTTPTest: 86
Infilteration: 337
SQL Injection: 29
SSH-Bruteforce: 184

In [1]:
# ============================================================
# CHRONEX DATASET AUDIT
# READ-ONLY DIAGNOSTIC
# ============================================================

import os
import json
import numpy as np
import pandas as pd

print("=" * 80)
print("CHRONEX DATASET AUDIT")
print("=" * 80)


# ------------------------------------------------------------
# 1. ENVIRONMENT
# ------------------------------------------------------------

print("\n[1] ENVIRONMENT")
print("-" * 80)

print("Working directory:")
print(os.getcwd())

print("\nFiles in current directory:")
for f in os.listdir("."):
    print("  ", f)


# ------------------------------------------------------------
# 2. FIND NPZ / JSON / JOBLIB FILES
# ------------------------------------------------------------

print("\n[2] AVAILABLE DATA ARTIFACTS")
print("-" * 80)

extensions = [".npz", ".json", ".joblib"]

for root, dirs, files in os.walk("."):
    for f in files:
        if any(f.lower().endswith(ext) for ext in extensions):
            print(os.path.join(root, f))


# ------------------------------------------------------------
# 3. LOCATE DATASET
# ------------------------------------------------------------

print("\n[3] DATASET")
print("-" * 80)

possible_npz = [
    "./data/processed/model_ready/dataset.npz",
    "./dataset.npz",
    "dataset.npz"
]

dataset_path = None

for p in possible_npz:
    if os.path.exists(p):
        dataset_path = p
        break

if dataset_path is None:
    # Search recursively
    for root, dirs, files in os.walk("."):
        for f in files:
            if f == "dataset.npz":
                dataset_path = os.path.join(root, f)
                break
        if dataset_path:
            break

if dataset_path is None:
    print("❌ dataset.npz NOT FOUND")
else:
    print("Dataset:", dataset_path)

    data = np.load(dataset_path, allow_pickle=True)

    print("\nKeys:")
    for key in data.files:
        print("  ", key)

    for key in data.files:
        arr = data[key]
        print(f"\n{key}:")
        print("  shape:", arr.shape)
        print("  dtype:", arr.dtype)

        if arr.size > 0:
            print("  min:", np.nanmin(arr))
            print("  max:", np.nanmax(arr))
            print("  mean:", np.nanmean(arr))
            print("  std:", np.nanstd(arr))


# ------------------------------------------------------------
# 4. LOAD X/y
# ------------------------------------------------------------

print("\n[4] TRAIN / VALIDATION / TEST")
print("-" * 80)

if dataset_path:

    X_train = data["X_train"]
    X_val   = data["X_val"]
    X_test  = data["X_test"]

    y_train = data["y_train"]
    y_val   = data["y_val"]
    y_test  = data["y_test"]

    for name, arr in [
        ("X_train", X_train),
        ("X_val", X_val),
        ("X_test", X_test),
        ("y_train", y_train),
        ("y_val", y_val),
        ("y_test", y_test)
    ]:
        print(f"{name}: shape={arr.shape}, dtype={arr.dtype}")


# ------------------------------------------------------------
# 5. INPUT DIMENSIONS
# ------------------------------------------------------------

print("\n[5] MODEL INPUT DIMENSIONS")
print("-" * 80)

if dataset_path:

    print("Sequence length:", X_train.shape[1])
    print("Feature count:", X_train.shape[2])

    print("\nExpected CHRONEX:")
    print("  Sequence length = 10")
    print("  Features        = 71")

    print("\nChecks:")
    print("  Sequence length correct:",
          X_train.shape[1] == 10)

    print("  Feature count correct:",
          X_train.shape[2] == 71)


# ------------------------------------------------------------
# 6. LABEL DISTRIBUTION
# ------------------------------------------------------------

print("\n[6] LABEL DISTRIBUTION")
print("-" * 80)

def print_distribution(name, y):
    values, counts = np.unique(y, return_counts=True)

    print(f"\n{name}")
    print("-" * 40)

    total = len(y)

    for v, c in zip(values, counts):
        print(
            f"{str(v):30s} "
            f"{c:8d} "
            f"{c/total*100:8.3f}%"
        )

    print("Total:", total)


if dataset_path:
    print_distribution("TRAIN", y_train)
    print_distribution("VALIDATION", y_val)
    print_distribution("TEST", y_test)


# ------------------------------------------------------------
# 7. CLASS PRESENCE ACROSS SPLITS
# ------------------------------------------------------------

print("\n[7] CLASS PRESENCE ACROSS SPLITS")
print("-" * 80)

if dataset_path:

    train_classes = set(np.unique(y_train))
    val_classes   = set(np.unique(y_val))
    test_classes  = set(np.unique(y_test))

    all_classes = sorted(
        train_classes |
        val_classes |
        test_classes
    )

    print(
        f"{'CLASS':30s}"
        f"{'TRAIN':>10s}"
        f"{'VAL':>10s}"
        f"{'TEST':>10s}"
    )

    print("-" * 65)

    for cls in all_classes:
        print(
            f"{str(cls):30s}"
            f"{'YES' if cls in train_classes else 'NO':>10s}"
            f"{'YES' if cls in val_classes else 'NO':>10s}"
            f"{'YES' if cls in test_classes else 'NO':>10s}"
        )

    print("\nMissing from TRAIN:",
          sorted(all_classes - train_classes))

    print("Missing from VAL:",
          sorted(all_classes - val_classes))

    print("Missing from TEST:",
          sorted(all_classes - test_classes))


# ------------------------------------------------------------
# 8. LABEL ENCODER
# ------------------------------------------------------------

print("\n[8] LABEL ENCODER")
print("-" * 80)

label_encoder_path = "./data/processed/model_ready/label_encoder.joblib"

if os.path.exists(label_encoder_path):

    try:
        import joblib

        le = joblib.load(label_encoder_path)

        print("Encoder:", label_encoder_path)
        print("Classes:")
        for i, cls in enumerate(le.classes_):
            print(f"  {i:2d} -> {cls}")

        print("\nNumber of encoded classes:", len(le.classes_))

    except Exception as e:
        print("Could not load label encoder:")
        print(e)

else:
    print("label_encoder.joblib not found")


# ------------------------------------------------------------
# 9. METADATA
# ------------------------------------------------------------

print("\n[9] METADATA")
print("-" * 80)

metadata_path = "./data/processed/model_ready/metadata.json"

if os.path.exists(metadata_path):

    with open(metadata_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    print(json.dumps(metadata, indent=2))

else:
    print("metadata.json not found")


# ------------------------------------------------------------
# 10. CHECK FOR NaN / INF
# ------------------------------------------------------------

print("\n[10] NaN / INF CHECK")
print("-" * 80)

if dataset_path:

    for name, arr in [
        ("X_train", X_train),
        ("X_val", X_val),
        ("X_test", X_test)
    ]:

        print(
            f"{name}: "
            f"NaN={np.isnan(arr).sum():,}, "
            f"Inf={np.isinf(arr).sum():,}"
        )


# ------------------------------------------------------------
# 11. CHECK SCALE
# ------------------------------------------------------------

print("\n[11] SCALE CHECK")
print("-" * 80)

if dataset_path:

    for name, X in [
        ("TRAIN", X_train),
        ("VAL", X_val),
        ("TEST", X_test)
    ]:

        flat = X.reshape(-1, X.shape[-1])

        print(f"\n{name}")

        print("  Overall mean:", np.mean(flat))
        print("  Overall std :", np.std(flat))

        print("  Feature means:")
        print("   min =", np.min(np.mean(flat, axis=0)))
        print("   max =", np.max(np.mean(flat, axis=0)))

        print("  Feature stds:")
        print("   min =", np.min(np.std(flat, axis=0)))
        print("   max =", np.max(np.std(flat, axis=0)))


# ------------------------------------------------------------
# 12. LOAD SCALER
# ------------------------------------------------------------

print("\n[12] SCALER")
print("-" * 80)

scaler_path = "./data/processed/model_ready/scaler.joblib"

if os.path.exists(scaler_path):

    try:
        import joblib

        scaler = joblib.load(scaler_path)

        print("Scaler:", scaler_path)
        print("Type:", type(scaler).__name__)

        if hasattr(scaler, "n_features_in_"):
            print("n_features_in_:", scaler.n_features_in_)

        if hasattr(scaler, "mean_"):
            print("Number of scaler means:", len(scaler.mean_))

            print("\nFirst 10 scaler means:")
            print(scaler.mean_[:10])

        if hasattr(scaler, "scale_"):
            print("\nFirst 10 scaler std/scales:")
            print(scaler.scale_[:10])

    except Exception as e:
        print("Could not load scaler:")
        print(e)

else:
    print("scaler.joblib not found")


# ------------------------------------------------------------
# 13. FEATURE NAMES
# ------------------------------------------------------------

print("\n[13] FEATURE NAMES")
print("-" * 80)

feature_names = None

if "metadata" in locals():

    possible_keys = [
        "feature_columns",
        "feature_columns_order",
        "features",
        "model_features"
    ]

    for key in possible_keys:
        if key in metadata:
            feature_names = metadata[key]
            print("Found metadata key:", key)
            break

if feature_names is not None:

    print("Number of features:", len(feature_names))

    for i, feature in enumerate(feature_names):
        print(f"{i+1:3d}. {feature}")

else:
    print("Feature names not found in expected metadata keys.")


# ------------------------------------------------------------
# 14. ATTACK_RATIO CHECK
# ------------------------------------------------------------

print("\n[14] ATTACK_RATIO CHECK")
print("-" * 80)

if feature_names is not None:

    attack_ratio_present = any(
        "attack_ratio" in str(x).lower()
        for x in feature_names
    )

    print("attack_ratio present in model features:",
          attack_ratio_present)

    if attack_ratio_present:
        print("⚠️ WARNING: attack_ratio is still in model input.")

    else:
        print("✅ attack_ratio is NOT in model input.")


# ------------------------------------------------------------
# 15. FLOW_COUNT CHECK
# ------------------------------------------------------------

print("\n[15] FLOW_COUNT CHECK")
print("-" * 80)

if feature_names is not None:

    flow_count_present = any(
        str(x).lower() == "flow_count"
        for x in feature_names
    )

    print("flow_count present:", flow_count_present)


# ------------------------------------------------------------
# 16. TARGET / FEATURE LEAKAGE NAMES
# ------------------------------------------------------------

print("\n[16] POSSIBLE TARGET-LEAKAGE FEATURES")
print("-" * 80)

if feature_names is not None:

    suspicious_terms = [
        "label",
        "attack",
        "target",
        "class",
        "malicious",
        "benign"
    ]

    suspicious = []

    for feature in feature_names:

        name = str(feature).lower()

        if any(term in name for term in suspicious_terms):
            suspicious.append(feature)

    if suspicious:
        print("Potentially suspicious feature names:")
        for x in suspicious:
            print("  ⚠️", x)
    else:
        print("No obviously label-derived feature names detected.")


# ------------------------------------------------------------
# 17. SEQUENCE OVERLAP CHECK
# ------------------------------------------------------------

print("\n[17] SEQUENCE OVERLAP CHECK")
print("-" * 80)

print("""
IMPORTANT:
The arrays alone may not contain timestamps/window IDs.

If sequences were created like:

W1 W2 W3 ... W10 -> W11
W2 W3 W4 ... W11 -> W12
W3 W4 W5 ... W12 -> W13

then consecutive samples overlap heavily.

This cell cannot prove cross-split temporal leakage unless
window/day/time identifiers were preserved.

We therefore need to inspect the sequence-generation code
or preserved sequence metadata for a definitive answer.
""")


# ------------------------------------------------------------
# 18. FINAL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("AUDIT SUMMARY")
print("=" * 80)

if dataset_path:

    print("Dataset found             : ✅")
    print("Sequence length           :", X_train.shape[1])
    print("Feature count             :", X_train.shape[2])
    print("Train sequences           :", len(X_train))
    print("Validation sequences      :", len(X_val))
    print("Test sequences            :", len(X_test))
    print("Total sequences           :", len(X_train) + len(X_val) + len(X_test))

    print("\nClasses:")
    print("  Train:", len(np.unique(y_train)))
    print("  Val  :", len(np.unique(y_val)))
    print("  Test :", len(np.unique(y_test)))

    if feature_names is not None:
        print("\nFeature count from metadata:", len(feature_names))

print("\n" + "=" * 80)
print("END OF CHRONEX DATASET AUDIT")
print("=" * 80)

================================================================================
CHRONEX DATASET AUDIT
================================================================================

[1] ENVIRONMENT
--------------------------------------------------------------------------------
Working directory:
d:\sih26153-data-pipeline\notebooks

Files in current directory:
   01_explore_data.ipynb

[2] AVAILABLE DATA ARTIFACTS
--------------------------------------------------------------------------------

[3] DATASET
--------------------------------------------------------------------------------
❌ dataset.npz NOT FOUND

[4] TRAIN / VALIDATION / TEST
--------------------------------------------------------------------------------

[5] MODEL INPUT DIMENSIONS
--------------------------------------------------------------------------------

[6] LABEL DISTRIBUTION
--------------------------------------------------------------------------------

[7] CLASS PRESENCE ACROSS SPLITS
--------------------------------------------------------------------------------

[8] LABEL ENCODER
--------------------------------------------------------------------------------
label_encoder.joblib not found

[9] METADATA
--------------------------------------------------------------------------------
metadata.json not found

[10] NaN / INF CHECK
--------------------------------------------------------------------------------

[11] SCALE CHECK
--------------------------------------------------------------------------------

[12] SCALER
--------------------------------------------------------------------------------
scaler.joblib not found

[13] FEATURE NAMES
--------------------------------------------------------------------------------
Feature names not found in expected metadata keys.

[14] ATTACK_RATIO CHECK
--------------------------------------------------------------------------------

[15] FLOW_COUNT CHECK
--------------------------------------------------------------------------------

[16] POSSIBLE TARGET-LEAKAGE FEATURES
--------------------------------------------------------------------------------

[17] SEQUENCE OVERLAP CHECK
--------------------------------------------------------------------------------

IMPORTANT:
The arrays alone may not contain timestamps/window IDs.

If sequences were created like:

W1 W2 W3 ... W10 -> W11
W2 W3 W4 ... W11 -> W12
W3 W4 W5 ... W12 -> W13

then consecutive samples overlap heavily.

This cell cannot prove cross-split temporal leakage unless
window/day/time identifiers were preserved.

We therefore need to inspect the sequence-generation code
or preserved sequence metadata for a definitive answer.


================================================================================
AUDIT SUMMARY
================================================================================

================================================================================
END OF CHRONEX DATASET AUDIT
================================================================================

In [2]:
import json
import joblib
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
MODEL_READY = PROJECT_ROOT / "data" / "processed" / "model_ready"

dataset_path = MODEL_READY / "dataset.npz"
metadata_path = MODEL_READY / "metadata.json"
scaler_path = MODEL_READY / "scaler.joblib"
encoder_path = MODEL_READY / "label_encoder.joblib"

print("=" * 80)
print("CHRONEX DATASET AUDIT")
print("=" * 80)

# ============================================================
# 1. LOAD DATASET
# ============================================================

print("\n[1] DATASET")
print("-" * 80)

if not dataset_path.exists():
    print("❌ dataset.npz not found:")
    print(dataset_path)
else:
    data = np.load(dataset_path, allow_pickle=True)

    print("✅ Dataset found")
    print("Path:", dataset_path)

    print("\nKeys:")
    print(data.files)

    for key in data.files:
        arr = data[key]
        print(f"{key:12s} shape={arr.shape} dtype={arr.dtype}")


# ============================================================
# 2. TRAIN / VAL / TEST SHAPES
# ============================================================

if dataset_path.exists():

    print("\n[2] DATASET SHAPES")
    print("-" * 80)

    X_train = data["X_train"]
    X_val = data["X_val"]
    X_test = data["X_test"]

    y_train = data["y_train"]
    y_val = data["y_val"]
    y_test = data["y_test"]

    print("X_train:", X_train.shape)
    print("X_val  :", X_val.shape)
    print("X_test :", X_test.shape)

    print("y_train:", y_train.shape)
    print("y_val  :", y_val.shape)
    print("y_test :", y_test.shape)

    print("\nTotal sequences:",
          len(X_train) + len(X_val) + len(X_test))

    print("\nSequence length:", X_train.shape[1])
    print("Feature count:", X_train.shape[2])


# ============================================================
# 3. LABEL DISTRIBUTION
# ============================================================

if dataset_path.exists():

    print("\n[3] LABEL DISTRIBUTION")
    print("-" * 80)

    def distribution(name, y):
        values, counts = np.unique(y, return_counts=True)

        print(f"\n{name}")
        print(f"{'Label':35s}{'Count':>12s}{'Percent':>12s}")
        print("-" * 60)

        total = len(y)

        for value, count in zip(values, counts):
            print(
                f"{str(value):35s}"
                f"{count:12,d}"
                f"{count / total * 100:11.3f}%"
            )

    distribution("TRAIN", y_train)
    distribution("VALIDATION", y_val)
    distribution("TEST", y_test)


# ============================================================
# 4. CLASS PRESENCE
# ============================================================

if dataset_path.exists():

    print("\n[4] CLASS PRESENCE ACROSS SPLITS")
    print("-" * 80)

    train_classes = set(np.unique(y_train))
    val_classes = set(np.unique(y_val))
    test_classes = set(np.unique(y_test))

    all_classes = sorted(
        train_classes |
        val_classes |
        test_classes
    )

    print(
        f"{'CLASS':35s}"
        f"{'TRAIN':>10s}"
        f"{'VAL':>10s}"
        f"{'TEST':>10s}"
    )

    print("-" * 68)

    for cls in all_classes:
        print(
            f"{str(cls):35s}"
            f"{'YES' if cls in train_classes else 'NO':>10s}"
            f"{'YES' if cls in val_classes else 'NO':>10s}"
            f"{'YES' if cls in test_classes else 'NO':>10s}"
        )

    print("\nMissing from TRAIN:", sorted(all_classes - train_classes))
    print("Missing from VAL  :", sorted(all_classes - val_classes))
    print("Missing from TEST :", sorted(all_classes - test_classes))


# ============================================================
# 5. METADATA
# ============================================================

print("\n[5] METADATA")
print("-" * 80)

if metadata_path.exists():

    with open(metadata_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    print(json.dumps(metadata, indent=2))

else:
    print("❌ metadata.json not found")


# ============================================================
# 6. FEATURE LIST
# ============================================================

print("\n[6] FEATURE LIST")
print("-" * 80)

feature_names = None

if metadata_path.exists():

    for key in [
        "feature_columns",
        "feature_columns_order",
        "features",
        "model_features"
    ]:

        if key in metadata:
            feature_names = metadata[key]
            print("Metadata key:", key)
            break

if feature_names is not None:

    print("Feature count:", len(feature_names))

    for i, feature in enumerate(feature_names):
        print(f"{i+1:3d}. {feature}")

    print("\nattack_ratio present:",
          "attack_ratio" in [str(x).lower() for x in feature_names])

    print("flow_count present:",
          "flow_count" in [str(x).lower() for x in feature_names])


# ============================================================
# 7. NaN / INF
# ============================================================

if dataset_path.exists():

    print("\n[7] NaN / INF CHECK")
    print("-" * 80)

    for name, X in [
        ("X_train", X_train),
        ("X_val", X_val),
        ("X_test", X_test)
    ]:

        print(
            f"{name:10s} "
            f"NaN={np.isnan(X).sum():,} "
            f"Inf={np.isinf(X).sum():,}"
        )


# ============================================================
# 8. SCALER
# ============================================================

print("\n[8] SCALER")
print("-" * 80)

if scaler_path.exists():

    scaler = joblib.load(scaler_path)

    print("✅ Scaler found")
    print("Type:", type(scaler).__name__)

    if hasattr(scaler, "n_features_in_"):
        print("Features:", scaler.n_features_in_)

    if hasattr(scaler, "mean_"):
        print("Scaler means:", len(scaler.mean_))
        print("First 10:", scaler.mean_[:10])

    if hasattr(scaler, "scale_"):
        print("Scaler scales:", len(scaler.scale_))
        print("First 10:", scaler.scale_[:10])

else:
    print("❌ scaler.joblib not found")


# ============================================================
# 9. LABEL ENCODER
# ============================================================

print("\n[9] LABEL ENCODER")
print("-" * 80)

if encoder_path.exists():

    le = joblib.load(encoder_path)

    print("✅ Label encoder found")
    print("Number of classes:", len(le.classes_))

    for i, cls in enumerate(le.classes_):
        print(f"{i:3d} -> {cls}")

else:
    print("❌ label_encoder.joblib not found")


# ============================================================
# 10. SCALE STATISTICS
# ============================================================

if dataset_path.exists():

    print("\n[10] SCALE STATISTICS")
    print("-" * 80)

    for name, X in [
        ("TRAIN", X_train),
        ("VAL", X_val),
        ("TEST", X_test)
    ]:

        flat = X.reshape(-1, X.shape[-1])

        print(f"\n{name}")
        print("  Overall mean:", np.mean(flat))
        print("  Overall std :", np.std(flat))

        feature_means = np.mean(flat, axis=0)
        feature_stds = np.std(flat, axis=0)

        print("  Feature mean range:",
              np.min(feature_means),
              "to",
              np.max(feature_means))

        print("  Feature std range:",
              np.min(feature_stds),
              "to",
              np.max(feature_stds))


# ============================================================
# FINAL
# ============================================================

print("\n" + "=" * 80)
print("AUDIT COMPLETE")
print("=" * 80)

================================================================================
CHRONEX DATASET AUDIT
================================================================================

[1] DATASET
--------------------------------------------------------------------------------
✅ Dataset found
Path: d:\sih26153-data-pipeline\data\processed\model_ready\dataset.npz

Keys:
['X_train', 'y_train', 'X_val', 'y_val', 'X_test', 'y_test']
X_train      shape=(6766, 10, 71) dtype=float32
y_train      shape=(6766,) dtype=int64
X_val        shape=(1451, 10, 71) dtype=float32
y_val        shape=(1451,) dtype=int64
X_test       shape=(1457, 10, 71) dtype=float32
y_test       shape=(1457,) dtype=int64

[2] DATASET SHAPES
--------------------------------------------------------------------------------
X_train: (6766, 10, 71)
X_val  : (1451, 10, 71)
X_test : (1457, 10, 71)
y_train: (6766,)
y_val  : (1451,)
y_test : (1457,)

Total sequences: 9674

Sequence length: 10
Feature count: 71

[3] LABEL DISTRIBUTION
--------------------------------------------------------------------------------

TRAIN
Label                                     Count     Percent
------------------------------------------------------------
0                                         5,521     81.599%
1                                           362      5.350%
2                                            25      0.369%
3                                           111      1.641%
4                                            46      0.680%
6                                            24      0.355%
7                                            33      0.488%
8                                             8      0.118%
9                                            86      1.271%
12                                          337      4.981%
13                                           29      0.429%
14                                          184      2.719%

VALIDATION
Label                                     Count     Percent
------------------------------------------------------------
0                                           616     42.453%
1                                           156     10.751%
2                                           155     10.682%
5                                            19      1.309%
6                                           118      8.132%
9                                             7      0.482%
10                                           69      4.755%
11                                          132      9.097%
12                                          179     12.336%

TEST
Label                                     Count     Percent
------------------------------------------------------------
0                                         1,117     76.664%
1                                           156     10.707%
5                                            35      2.402%
6                                             9      0.618%
10                                           16      1.098%
11                                           64      4.393%
12                                           60      4.118%

[4] CLASS PRESENCE ACROSS SPLITS
--------------------------------------------------------------------------------
CLASS                                   TRAIN       VAL      TEST
--------------------------------------------------------------------
0                                         YES       YES       YES
1                                         YES       YES       YES
2                                         YES       YES        NO
3                                         YES        NO        NO
4                                         YES        NO        NO
5                                          NO       YES       YES
6                                         YES       YES       YES
7                                         YES        NO        NO
8                                         YES        NO        NO
9                                         YES       YES        NO
10                                         NO       YES       YES
11                                         NO       YES       YES
12                                        YES       YES       YES
13                                        YES        NO        NO
14                                        YES        NO        NO

TypeError: unsupported operand type(s) for -: 'list' and 'set'

In [3]:
import os
import pandas as pd

PROCESSED_DIR = "../data/processed"

constant_cols = [
    'Bwd Blk Rate Avg',
    'Fwd Pkts/b Avg',
    'Bwd Byts/b Avg',
    'Bwd URG Flags',
    'Bwd PSH Flags',
    'Fwd Byts/b Avg',
    'Bwd Pkts/b Avg',
    'Fwd Blk Rate Avg'
]

files = sorted(
    f for f in os.listdir(PROCESSED_DIR)
    if f.startswith("cleaned_") and f.endswith(".csv")
)

for fname in files:
    path = os.path.join(PROCESSED_DIR, fname)
    df = pd.read_csv(path, usecols=lambda c: c in constant_cols)

    print(f"\n{fname}")
    for col in constant_cols:
        if col in df.columns:
            print(
                f"{col:20s} "
                f"unique={df[col].nunique(dropna=False)} "
                f"min={df[col].min()} "
                f"max={df[col].max()}"
            )

cleaned_02-14-2018.csv

cleaned_02-15-2018.csv

cleaned_02-16-2018.csv

cleaned_02-20-2018.csv

cleaned_02-21-2018.csv

cleaned_02-22-2018.csv

cleaned_02-23-2018.csv

cleaned_02-28-2018.csv

cleaned_03-01-2018.csv

cleaned_03-02-2018.csv

In [4]:
import pandas as pd

log = pd.read_csv("../data/processed/cleaning_log.csv")

log["loss_pct"] = (
    (log["rows_before"] - log["rows_after"])
    / log["rows_before"]
    * 100
)

display(
    log[
        [
            "filename",
            "rows_before",
            "dropped_invalid",
            "dropped_bad_timestamp",
            "dropped_duplicates",
            "rows_after",
            "loss_pct"
        ]
    ].sort_values("loss_pct", ascending=False)
)

,filename,rows_before,dropped_invalid,dropped_bad_timestamp,dropped_duplicates,rows_after,loss_pct
7,02-28-2018.csv,613104,4074,0,138575,470455,23.266689
0,02-14-2018.csv,1048575,3824,5,225625,819121,21.882460
2,02-16-2018.csv,1048575,1,0,147586,900988,14.075007
4,02-21-2018.csv,1048575,0,0,17557,1031018,1.674368
3,02-20-2018.csv,7948748,59453,0,22440,7866855,1.030263
1,02-15-2018.csv,1048575,8027,0,2416,1038132,0.995923
9,03-02-2018.csv,1048575,4050,0,5453,1039072,0.906278
5,02-22-2018.csv,1048575,5610,9,3272,1039684,0.847913
6,02-23-2018.csv,1048575,5708,0,2612,1040255,0.793458
8,03-01-2018.csv,331125,1859,0,73,329193,0.583465

In [5]:
import os
import pandas as pd

PROCESSED_DIR = "../data/processed"

constant_cols = [
    'Bwd Blk Rate Avg',
    'Fwd Pkts/b Avg',
    'Bwd Byts/b Avg',
    'Bwd URG Flags',
    'Bwd PSH Flags',
    'Fwd Byts/b Avg',
    'Bwd Pkts/b Avg',
    'Fwd Blk Rate Avg'
]

files = sorted(
    f for f in os.listdir(PROCESSED_DIR)
    if f.startswith("cleaned_") and f.endswith(".csv")
)

for fname in files:
    path = os.path.join(PROCESSED_DIR, fname)
    df = pd.read_csv(path, usecols=lambda c: c in constant_cols)

    print(f"\n{fname}")
    for col in constant_cols:
        if col in df.columns:
            print(
                f"{col:20s} "
                f"unique={df[col].nunique(dropna=False)} "
                f"min={df[col].min()} "
                f"max={df[col].max()}"
            )

cleaned_02-14-2018.csv

cleaned_02-15-2018.csv

cleaned_02-16-2018.csv

cleaned_02-20-2018.csv

cleaned_02-21-2018.csv

cleaned_02-22-2018.csv

cleaned_02-23-2018.csv

cleaned_02-28-2018.csv

cleaned_03-01-2018.csv

cleaned_03-02-2018.csv

In [6]:
import os
import pandas as pd

PROCESSED_DIR = "../data/processed"

constant_cols = [
    'Bwd Blk Rate Avg',
    'Fwd Pkts/b Avg',
    'Bwd Byts/b Avg',
    'Bwd URG Flags',
    'Bwd PSH Flags',
    'Fwd Byts/b Avg',
    'Bwd Pkts/b Avg',
    'Fwd Blk Rate Avg'
]

files = sorted(
    f for f in os.listdir(PROCESSED_DIR)
    if f.startswith("cleaned_") and f.endswith(".csv")
)

for fname in files:
    path = os.path.join(PROCESSED_DIR, fname)
    df = pd.read_csv(path)

    print(f"\n===== {fname} =====")

    for col in constant_cols:
        if col in df.columns:
            print(
                f"{col:20s} "
                f"unique={df[col].nunique(dropna=False)} "
                f"min={df[col].min()} "
                f"max={df[col].max()}"
            )
        else:
            print(f"{col:20s} MISSING")

===== cleaned_02-14-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

===== cleaned_02-15-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

===== cleaned_02-16-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

===== cleaned_02-20-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

===== cleaned_02-21-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

===== cleaned_02-22-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

===== cleaned_02-23-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

===== cleaned_02-28-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

===== cleaned_03-01-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

===== cleaned_03-02-2018.csv =====
Bwd Blk Rate Avg     MISSING
Fwd Pkts/b Avg       MISSING
Bwd Byts/b Avg       MISSING
Bwd URG Flags        MISSING
Bwd PSH Flags        MISSING
Fwd Byts/b Avg       MISSING
Bwd Pkts/b Avg       MISSING
Fwd Blk Rate Avg     MISSING

In [7]:
import os
import pandas as pd
import numpy as np

RAW_DIR = "../data/raw"

constant_cols = [
    'Bwd Blk Rate Avg',
    'Fwd Pkts/b Avg',
    'Bwd Byts/b Avg',
    'Bwd URG Flags',
    'Bwd PSH Flags',
    'Fwd Byts/b Avg',
    'Bwd Pkts/b Avg',
    'Fwd Blk Rate Avg'
]

files = sorted(
    f for f in os.listdir(RAW_DIR)
    if f.endswith(".csv")
)

for fname in files:
    print(f"\n===== {fname} =====")

    # Only load the columns we care about
    df = pd.read_csv(
        os.path.join(RAW_DIR, fname),
        usecols=lambda c: c.strip() in constant_cols,
        low_memory=False
    )

    df.columns = df.columns.str.strip()

    for col in constant_cols:
        if col in df.columns:
            s = pd.to_numeric(df[col], errors="coerce")
            print(
                f"{col:20s} "
                f"unique={s.nunique(dropna=False)} "
                f"min={s.min()} "
                f"max={s.max()}"
            )
        else:
            print(f"{col:20s} MISSING")

===== 02-14-2018.csv =====
Bwd Blk Rate Avg     unique=1 min=0 max=0
Fwd Pkts/b Avg       unique=1 min=0 max=0
Bwd Byts/b Avg       unique=1 min=0 max=0
Bwd URG Flags        unique=1 min=0 max=0
Bwd PSH Flags        unique=1 min=0 max=0
Fwd Byts/b Avg       unique=1 min=0 max=0
Bwd Pkts/b Avg       unique=1 min=0 max=0
Fwd Blk Rate Avg     unique=1 min=0 max=0

===== 02-15-2018.csv =====
Bwd Blk Rate Avg     unique=1 min=0 max=0
Fwd Pkts/b Avg       unique=1 min=0 max=0
Bwd Byts/b Avg       unique=1 min=0 max=0
Bwd URG Flags        unique=1 min=0 max=0
Bwd PSH Flags        unique=1 min=0 max=0
Fwd Byts/b Avg       unique=1 min=0 max=0
Bwd Pkts/b Avg       unique=1 min=0 max=0
Fwd Blk Rate Avg     unique=1 min=0 max=0

===== 02-16-2018.csv =====
Bwd Blk Rate Avg     unique=2 min=0.0 max=0.0
Fwd Pkts/b Avg       unique=2 min=0.0 max=0.0
Bwd Byts/b Avg       unique=2 min=0.0 max=0.0
Bwd URG Flags        unique=2 min=0.0 max=0.0
Bwd PSH Flags        unique=2 min=0.0 max=0.0
Fwd Byts/b Avg       unique=2 min=0.0 max=0.0
Bwd Pkts/b Avg       unique=2 min=0.0 max=0.0
Fwd Blk Rate Avg     unique=2 min=0.0 max=0.0

===== 02-20-2018.csv =====

ParserError: Error tokenizing data. C error: out of memory

In [8]:
import joblib
import json
import numpy as np

base = "../data/processed/model_ready"

scaler = joblib.load(f"{base}/scaler.joblib")

with open(f"{base}/metadata.json", "r") as f:
    metadata = json.load(f)

data = np.load(f"{base}/dataset.npz")

print("=== DATASET ===")
for k in data.files:
    print(k, data[k].shape, data[k].dtype)

print("\n=== SCALER ===")
print("type:", type(scaler).__name__)
print("n_features_in_:", scaler.n_features_in_)
print("mean shape:", scaler.mean_.shape)
print("scale shape:", scaler.scale_.shape)
print("first 5 means:", scaler.mean_[:5])
print("first 5 scales:", scaler.scale_[:5])

print("\n=== METADATA ===")
print("n_features:", metadata.get("n_features"))
print("sequence_length:", metadata.get("sequence_length"))
print("window_seconds:", metadata.get("window_seconds"))
print("label_classes:", metadata.get("label_classes"))
print("feature count:", len(metadata.get("feature_columns_order", [])))

=== DATASET ===
X_train (6766, 10, 71) float32
y_train (6766,) int64
X_val (1451, 10, 71) float32
y_val (1451,) int64
X_test (1457, 10, 71) float32
y_test (1457,) int64

=== SCALER ===
type: StandardScaler
n_features_in_: 71
mean shape: (71,)
scale shape: (71,)
first 5 means: [8.17166632e+03 8.71571872e+00 1.67779181e+07 6.23701553e+00
 6.61643472e+00]
first 5 scales: [3.79467587e+03 1.70922067e+00 1.15624256e+07 3.68429525e+00
 6.45438901e+00]

=== METADATA ===
n_features: 71
sequence_length: 10
window_seconds: 30
label_classes: ['Benign', 'Bot', 'Brute Force -Web', 'Brute Force -XSS', 'DDOS attack-HOIC', 'DDOS attack-LOIC-UDP', 'DDoS attacks-LOIC-HTTP', 'DoS attacks-GoldenEye', 'DoS attacks-Hulk', 'DoS attacks-SlowHTTPTest', 'DoS attacks-Slowloris', 'FTP-BruteForce', 'Infilteration', 'SQL Injection', 'SSH-Bruteforce']
feature count: 71

In [9]:
import numpy as np
from sklearn.model_selection import train_test_split

BASE = "../data/processed/model_ready"
data = np.load(f"{BASE}/dataset.npz")

# Pool the EXISTING sequences
X = np.concatenate([
    data["X_train"],
    data["X_val"],
    data["X_test"]
], axis=0)

y = np.concatenate([
    data["y_train"],
    data["y_val"],
    data["y_test"]
], axis=0)

print("TOTAL X:", X.shape)
print("TOTAL y:", y.shape)

# 70% train, 30% temporary
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

# 15% val, 15% test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

print("\nFINAL SHAPES")
print("Train:", X_train.shape, y_train.shape)
print("Val:  ", X_val.shape, y_val.shape)
print("Test: ", X_test.shape, y_test.shape)

print("\nCLASS COUNTS")

for split_name, labels in [
    ("TRAIN", y_train),
    ("VAL", y_val),
    ("TEST", y_test)
]:
    classes, counts = np.unique(labels, return_counts=True)

    print(f"\n{split_name}")
    for c, n in zip(classes, counts):
        print(f"  class {c:2d}: {n}")

    print("  Number of classes:", len(classes))

TOTAL X: (9674, 10, 71)
TOTAL y: (9674,)

FINAL SHAPES
Train: (6771, 10, 71) (6771,)
Val:   (1451, 10, 71) (1451,)
Test:  (1452, 10, 71) (1452,)

CLASS COUNTS

TRAIN
  class  0: 5077
  class  1: 472
  class  2: 126
  class  3: 78
  class  4: 32
  class  5: 38
  class  6: 106
  class  7: 23
  class  8: 6
  class  9: 65
  class 10: 59
  class 11: 137
  class 12: 403
  class 13: 20
  class 14: 129
  Number of classes: 15

VAL
  class  0: 1088
  class  1: 101
  class  2: 27
  class  3: 17
  class  4: 7
  class  5: 8
  class  6: 23
  class  7: 5
  class  8: 1
  class  9: 14
  class 10: 13
  class 11: 29
  class 12: 86
  class 13: 5
  class 14: 27
  Number of classes: 15

TEST
  class  0: 1089
  class  1: 101
  class  2: 27
  class  3: 16
  class  4: 7
  class  5: 8
  class  6: 22
  class  7: 5
  class  8: 1
  class  9: 14
  class 10: 13
  class 11: 30
  class 12: 87
  class 13: 4
  class 14: 28
  Number of classes: 15

In [10]:
# Compact verification only
expected_classes = set(range(15))

for name, labels in [
    ("TRAIN", y_train),
    ("VAL", y_val),
    ("TEST", y_test),
]:
    classes = set(np.unique(labels))
    print(
        f"{name}: "
        f"{len(classes)}/15 classes | "
        f"missing = {sorted(expected_classes - classes)}"
    )

TRAIN: 15/15 classes | missing = []
VAL: 15/15 classes | missing = []
TEST: 15/15 classes | missing = []

In [11]:
import numpy as np
import joblib

BASE = "../data/processed/model_ready"

data = np.load(f"{BASE}/dataset.npz")
scaler = joblib.load(f"{BASE}/scaler.joblib")

X_scaled = data["X_train"]

# Recover raw/original values
X_raw = scaler.inverse_transform(
    X_scaled.reshape(-1, X_scaled.shape[-1])
).reshape(X_scaled.shape)

# Scale them again
X_scaled_again = scaler.transform(
    X_raw.reshape(-1, X_raw.shape[-1])
).reshape(X_raw.shape)

# Check reconstruction error
max_error = np.max(np.abs(X_scaled - X_scaled_again))
mean_error = np.mean(np.abs(X_scaled - X_scaled_again))

print("Original scaled shape :", X_scaled.shape)
print("Recovered raw shape   :", X_raw.shape)
print("Max reconstruction error :", max_error)
print("Mean reconstruction error:", mean_error)

# Show a few raw values
print("\nFirst sequence, first timestep, first 5 raw features:")
print(X_raw[0, 0, :5])

Original scaled shape : (6766, 10, 71)
Recovered raw shape   : (6766, 10, 71)
Max reconstruction error : 4.7683716e-07
Mean reconstruction error: 9.387106e-10

First sequence, first timestep, first 5 raw features:
[3.5330901e+03 1.1394972e+01 1.4074454e+07 5.9967561e+00 7.2733173e+00]

In [12]:
import numpy as np
import joblib
from sklearn.preprocessing import StandardScaler

BASE = "../data/processed/model_ready"

data = np.load(f"{BASE}/dataset.npz")
old_scaler = joblib.load(f"{BASE}/scaler.joblib")

# 1. Pool existing scaled data
X_all_scaled = np.concatenate(
    [data["X_train"], data["X_val"], data["X_test"]],
    axis=0
)

y_all = np.concatenate(
    [data["y_train"], data["y_val"], data["y_test"]],
    axis=0
)

# 2. Recover raw/original feature values
n_features = X_all_scaled.shape[-1]

X_all_raw = old_scaler.inverse_transform(
    X_all_scaled.reshape(-1, n_features)
).reshape(X_all_scaled.shape)

# 3. Use the SAME verified stratified split
from sklearn.model_selection import train_test_split

X_train_raw, X_temp_raw, y_train, y_temp = train_test_split(
    X_all_raw,
    y_all,
    test_size=0.30,
    stratify=y_all,
    random_state=42
)

X_val_raw, X_test_raw, y_val, y_test = train_test_split(
    X_temp_raw,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

# 4. Fit NEW scaler ONLY on training data
new_scaler = StandardScaler()

new_scaler.fit(
    X_train_raw.reshape(-1, n_features)
)

# 5. Transform all splits using that same scaler
X_train_new = new_scaler.transform(
    X_train_raw.reshape(-1, n_features)
).reshape(X_train_raw.shape).astype(np.float32)

X_val_new = new_scaler.transform(
    X_val_raw.reshape(-1, n_features)
).reshape(X_val_raw.shape).astype(np.float32)

X_test_new = new_scaler.transform(
    X_test_raw.reshape(-1, n_features)
).reshape(X_test_raw.shape).astype(np.float32)

# 6. Checks
print("Shapes:")
print("Train:", X_train_new.shape, y_train.shape)
print("Val:  ", X_val_new.shape, y_val.shape)
print("Test: ", X_test_new.shape, y_test.shape)

print("\nFinite check:")
print("Train:", np.isfinite(X_train_new).all())
print("Val:  ", np.isfinite(X_val_new).all())
print("Test: ", np.isfinite(X_test_new).all())

print("\nScaler:")
print("Features:", new_scaler.n_features_in_)
print("First 5 new means:", new_scaler.mean_[:5])
print("First 5 new scales:", new_scaler.scale_[:5])

Shapes:
Train: (6771, 10, 71) (6771,)
Val:   (1451, 10, 71) (1451,)
Test:  (1452, 10, 71) (1452,)

Finite check:
Train: True
Val:   True
Test:  True

Scaler:
Features: 71
First 5 new means: [8.10856941e+03 8.74725657e+00 1.69727977e+07 6.24093759e+00
 6.48954381e+00]
First 5 new scales: [3.70739144e+03 1.70943632e+00 1.26627419e+07 3.78002261e+00
 5.97795879e+00]

In [13]:
# DIAGNOSTIC CELL — Run this FIRST to verify state

import numpy as np
import torch
import json

print("="*80)
print("CHRONEX PRE-BUILD DIAGNOSTIC")
print("="*80)

# Check 1: Model loaded?
try:
    checkpoint = torch.load("/content/trained_lstm_binary.pt", map_location="cpu")
    print("\n✅ Model checkpoint exists")
    print(f"   Input size: {checkpoint['input_size']}")
    print(f"   Num classes: {checkpoint['num_classes']}")
    
    # Reload model for later use
    class BinaryAttackForecastLSTM(torch.nn.Module):
        def __init__(self, input_size, hidden_size=64):
            super().__init__()
            self.lstm = torch.nn.LSTM(input_size, hidden_size, batch_first=True)
            self.dropout = torch.nn.Dropout(0.3)
            self.fc = torch.nn.Linear(hidden_size, 2)
        def forward(self, x):
            out, _ = self.lstm(x)
            last_step = self.dropout(out[:, -1, :])
            return self.fc(last_step)
    
    model = BinaryAttackForecastLSTM(input_size=checkpoint['input_size'])
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    print("✅ Model reloaded successfully")
    MODEL_OK = True
except Exception as e:
    print(f"\n❌ Model error: {e}")
    MODEL_OK = False

# Check 2: Dataset loaded?
try:
    data = np.load("/content/dataset.npz")
    X_train = data["X_train"]
    X_val = data["X_val"]
    X_test = data["X_test"]
    y_train = data["y_train"]
    y_val = data["y_val"]
    y_test = data["y_test"]
    
    print(f"\n✅ Dataset loaded")
    print(f"   X_train shape: {X_train.shape}")
    print(f"   X_test shape: {X_test.shape}")
    print(f"   y_test distribution: Benign={np.sum(y_test==0)}, Attack={np.sum(y_test==1)}")
    DATASET_OK = True
except Exception as e:
    print(f"\n❌ Dataset error: {e}")
    DATASET_OK = False

# Check 3: Metadata loaded?
try:
    with open("/content/metadata.json") as f:
        metadata = json.load(f)
    feature_columns = metadata["feature_columns_order"]
    print(f"\n✅ Metadata loaded")
    print(f"   Feature count: {len(feature_columns)}")
    print(f"   Features: {feature_columns[:5]}... (showing first 5)")
    METADATA_OK = True
except Exception as e:
    print(f"\n❌ Metadata error: {e}")
    METADATA_OK = False

print("\n" + "="*80)
if MODEL_OK and DATASET_OK and METADATA_OK:
    print("✅ ALL SYSTEMS READY — Proceeding with feature build")
    print("="*80)
else:
    print("❌ MISSING COMPONENTS — Cannot proceed")
    print("="*80)

ModuleNotFoundError: No module named 'torch'